[versions]

# Minecraft
fabricLoader = "0.18.4"
fabricKt = "1.13.7+kotlin.2.2.21"
loom = "1.12-SNAPSHOT"

# Dependencies
objc = "1.2"

# Dev Dependencies
devauth = "1.2.1"

[libraries]

fabricLoader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabricKt = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricKt" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

objc = { module = "ca.weblite:java-objc-bridge", version.ref = "objc" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }